version: "3.9"
volumes:
  db-store:
services:
  db:
    build: ./infra/mariadb
    ports:
      - 13306:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db-store:/var/lib/mysql
  web:
    build: ./infra/nginx
    ports:
      # - 8000:8000
      - 80:80
    environment:
      TZ: Asia/Tokyo
    # volumes:
    # - ./api:/work/api
    # - ./logs/nginx:/var/log/nginx
    # - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    # working_dir: /work
    depends_on:
      - api
      # - nuxt
  api:
    build: ./infra/api
    volumes:
      - ./api:/app
    expose:
      - 8000
  # selenium:
  #   image: selenium/standalone-chrome:4.0.0-beta-3-20210426
  #   shm_size: "2gb"
  #   ports:
  #     - 4444:4444
  #     - 5900:5900
  #   depends_on:
  #     - web
